### ISSUE TITLE
creacion de CRUD'S de tablas para la creacion de un curso

### ISSUE THREAD

**Issue by RichardTM** [RichardTM/leinlanic#5]
**creacion de CRUD'S de tablas para la creacion de un curso**
**TABLAS:**
→ _lengua_
→ _desarrolladores_
→ _cursos_
→ _niveles_
→ _lecciones_
→ _actividades_
→ _respuestas_
→ _preguntas_
→ _tipo_preguntas_

**Comment by Jhosell** [comment]
CRUDS terminados:
→ cursos
→ niveles
→ lecciones

**Comment by jhonatanMr2105** [comment]
CRUDS terminados:
→ cursos
→ lengua
→desarrolladores
